const actions = {
  GET_FINISH_TEAM_ID_PER_USER_STATUS: "GET_FINISH_TEAM_ID_PER_USER_STATUS",
  GET_FINISH_TEAM_ID_PER_USER_STATUS_SUCCESS: "GET_FINISH_TEAM_ID_PER_USER_STATUS_SUCCESS",
  GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS: "GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS",
  GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS_SUCCESS: "GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS_SUCCESS",
  GET_FINISH_TOTAL_HASH_PER_USER_STATUS: "GET_FINISH_TOTAL_HASH_PER_USER_STATUS",
  GET_FINISH_TOTAL_HASH_PER_USER_STATUS_SUCCESS: "GET_FINISH_TOTAL_HASH_PER_USER_STATUS_SUCCESS",
  GET_FINISH_TOTAL_POWER_PER_TEAM_STATUS: "GET_FINISH_TOTAL_POWER_PER_TEAM_STATUS",
  GET_FINISH_TOTAL_POWER_PER_TEAM_STATUS_SUCCESS: "GET_FINISH_TOTAL_POWER_PER_TEAM_STATUS_SUCCESS",
  GET_FINISH_TOTAL_POWER_PER_USER_STATUS: "GET_FINISH_TOTAL_POWER_PER_USER_STATUS",
  GET_FINISH_TOTAL_POWER_PER_USER_STATUS_SUCCESS: "GET_FINISH_TOTAL_POWER_PER_USER_STATUS_SUCCESS",
  GET_FINISH_TOTAL_NDR_PER_TEAM_STATUS: "GET_FINISH_TOTAL_NDR_PER_TEAM_STATUS",
  GET_FINISH_TOTAL_NDR_PER_TEAM_STATUS_SUCCESS: "GET_FINISH_TOTAL_NDR_PER_TEAM_STATUS_SUCCESS",
  GET_FINISH_TOTAL_NDR_PER_USER_STATUS: "GET_FINISH_TOTAL_NDR_PER_USER_STATUS",
  GET_FINISH_TOTAL_NDR_PER_USER_STATUS_SUCCESS: "GET_FINISH_TOTAL_NDR_PER_USER_STATUS_SUCCESS",
  GET_FINISH_TEAM_PLAYERS_COUNT_STATUS: "GET_FINISH_TEAM_PLAYERS_COUNT_STATUS",
  GET_FINISH_TEAM_PLAYERS_COUNT_STATUS_SUCCESS: "GET_FINISH_TEAM_PLAYERS_COUNT_STATUS_SUCCESS",
  
  UN_STAKE_ALL: "UN_STAKE_ALL",
  GET_FINISHED_STAKED_CARDS: "GET_FINISHED_STAKED_CARDS",
  GET_FINISHED_STAKED_CARDS_SUCCESS: "GET_FINISHED_STAKED_CARDS_SUCCESS",
  GET_EMPTY_STAKED_CARDS: "GET_EMPTY_STAKED_CARDS",
  GET_EMPTY_STAKED_CARDS_SUCCESS: "GET_EMPTY_STAKED_CARDS_SUCCESS", 

  getFinishedStakedCards: () => ({
    type: actions.GET_FINISHED_STAKED_CARDS,
    payload: {}
  }),
  getEmptyStakedCards: () => ({
    type: actions.GET_EMPTY_STAKED_CARDS,
    payload: {}
  }),
  getFinishTeamIdPerUserStatus: () => ({
    type: actions.GET_FINISH_TEAM_ID_PER_USER_STATUS,
    payload: {}
  }),
  getFinishTotalHashPerTeamStatus: () => ({
    type: actions.GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS,
    payload: {}
  }),
  getFinishTotalHashPerUserStatus: (openRound) => ({
    type: actions.GET_FINISH_TOTAL_HASH_PER_USER_STATUS,
    payload: {openRound}
  }),
  getFinishTotalPowerPerTeamStatus: (openRound, openTeam) => ({
    type: actions.GET_FINISH_TOTAL_POWER_PER_TEAM_STATUS,
    payload: {openRound, openTeam}
  }),
  getFinishTotalPowerPerUserStatus: (openRound) => ({
    type: actions.GET_FINISH_TOTAL_POWER_PER_USER_STATUS,
    payload: {openRound}
  }),
  getFinishTotalNDRPerTeamStatus: (openRound, openTeam) => ({
    type: actions.GET_FINISH_TOTAL_NDR_PER_TEAM_STATUS,
    payload: {openRound, openTeam}
  }),
  getFinishTotalNDRPerUserStatus: (openRound) => ({
    type: actions.GET_FINISH_TOTAL_NDR_PER_USER_STATUS,
    payload: {openRound}
  }),
  getFinishTeamPlayersCountStatus: (openRound, openTeam) => ({
    type: actions.GET_FINISH_TEAM_PLAYERS_COUNT_STATUS,
    payload: {openRound, openTeam}
  }),
  unstakeAll: (openRound, callback) => ({
    type: actions.UN_STAKE_ALL,
    payload: {openRound, callback}
  }),
};

export default actions;
